### ISSUE TITLE
TODO for the Reboot code

### ISSUE THREAD

**Issue by icydee** [plainblack/Lacuna-Web-Client#208]
Things that need to be done in the REBOOT code but which don't need a separate issue.

- [ ] Convert all Empire calls to use named calling convention
- [ ] Convert all Map calls to use named calling convention
- [ ] Convert all Body calls to use named calling convention
- [ ] Reactify a new starmap
- [ ] lots more things...
